name: Deploy Angular to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npx ng build --configuration production

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/GitHubActionsDeployRole
          aws-region: us-east-1

      # 🔥 Upload static assets with long cache
      - name: Upload static assets
        run: |
          aws s3 sync dist/horrocruxes/ s3://horrocruxes-harrypotter-rag.me \
            --delete \
            --exclude "index.html" \
            --cache-control "max-age=31536000,public"

      # 🔥 Upload index.html with no cache
      - name: Upload index.html
        run: |
          aws s3 cp dist/horrocruxes/index.html \
            s3://horrocruxes-harrypotter-rag.me/index.html \
            --cache-control "no-cache"

      - name: CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DIST_ID }} \
            --paths "/index.html"